#13 add log4j2 starter, delete log4j.properties and dependency
SashaHapon/Web pull request #18
Opened 2024-01-17 12:21 UTC by SashaHapon

2024-01-17 12:35 UTC, drasolka commented on pom.xml
> +            <artifactId>spring-boot-starter-log4j2</artifactId>
Посмотри внимательно, как конфигурировать log4j2 для spring boot https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.logging.log4j

2024-01-18 07:24 UTC, drasolka commented on src/main/resources/logs/log4j.log
Неправильно иметь вывод лога в проектных файлах в репозитории.
Вопрос: почему?

2024-01-18 08:39 UTC, SashaHapon commented on src/main/resources/logs/log4j.log
я думаю основная причина, потому постоянно надо  будет коммит, потому-что файл будет обновляться.
вторая в том, что лог для отладки и мониторинга, а поэтому выкладывать в репозиторий не имеет смысла.

я понимал, что это скорее не правильно, но сделал это потому что так наглядно видно что задача решена.
впредь буду знать

2024-01-18 13:07 UTC, drasolka requested changes

2024-01-18 13:07 UTC, drasolka commented on .gitignore
> +/src/main/resources/logs
Файлы в данной директории все равно будут попадать в сборку проекта, но не будут попадать в гит.

2024-01-18 13:07 UTC, drasolka commented on src/main/resources/logback.xml
> +        <file>src/main/resources/logs/log4j.log</file> <!-- Укажите путь к файлу логов -->
Файлы журнала логов необходимо указывать во внешнюю директорию по отношению к проекту, либо в корень проекта(не отменяет игнорирование его гитом).

2024-01-19 07:24 UTC, drasolka approved these changes

2024-01-19 07:25 UTC, merged