19
SashaHapon/Web pull request #36
Opened 2024-01-29 08:58 UTC by SashaHapon

2024-02-02 09:51 UTC, drasolka requested changes

2024-02-02 09:51 UTC, drasolka commented on src/main/java/org/food/controller/AccountController.java
> +    public AccountDto addAccount(@RequestBody AccountDto accountDto) throws HttpMessageNotReadableException {
В каких случаях возникает `HttpMessageNotReadableException`?

2024-02-02 09:51 UTC, drasolka commented on src/main/java/org/food/dao/AbstractDao.java
> +        return entityManager.createQuery("SELECT e FROM " + entityClass.getSimpleName() + " e", entityClass)
Куда делать пагинация, котороя есть в декларации метода?

2024-02-02 09:51 UTC, drasolka commented on src/main/java/org/food/exception/ControllerExceptionHandler.java
> +import jakarta.persistence.EntityNotFoundException;
Не правильно обрабатывать ошибки при работе с БД на презентационном уровне. Необходимо заменять такие ошибки на свои собственные.

2024-02-02 09:51 UTC, drasolka commented on src/main/java/org/food/service/AccountServiceImpl.java
> +import org.springframework.http.HttpHeaders;
Лишний импорт.

2024-02-02 09:51 UTC, drasolka commented on src/main/java/org/food/service/AccountServiceImpl.java
> +import org.springframework.web.client.HttpClientErrorException;
Лишний импорт. Нельзя смешивать слои приложения. Ошибка презентационного уровня должна оставаться на своем уровне, а не использоваться на уровне ниже.

2024-02-02 09:51 UTC, drasolka commented on src/test/java/org/food/integration/AccountIntegrationTest.java
> +@AutoConfigureMockMvc(addFilters = false)
На сколько я понимаю, это для того, чтобы отключить проверку токенов?
Является ли данный тест полноценным интеграционным тестом?

2024-02-02 09:51 UTC, drasolka commented on src/test/java/org/food/integration/AccountIntegrationTest.java
> +        AccountDto response = objectMapper.readValue(contentAsString, AccountDto.class);
Зачем эти действия, если нет асерта для этих данных?
Тестировать json результаты можно с помощью `.andExpect(content().json(<your-json>)`, ожидаемые данны можно брать из внешних файлов.

2024-02-02 10:41 UTC, SashaHapon commented on src/main/java/org/food/controller/AccountController.java
> +    public AccountDto addAccount(@RequestBody AccountDto accountDto) throws HttpMessageNotReadableException {
когда возникает ошибка при десериализации

2024-02-02 11:14 UTC, SashaHapon commented on src/main/java/org/food/dao/AbstractDao.java
> +        return entityManager.createQuery("SELECT e FROM " + entityClass.getSimpleName() + " e", entityClass)
скрипт не работал, переписал с использованием CriteriaAPI, скоро залью на гитхаб

2024-02-02 13:10 UTC, SashaHapon commented on src/test/java/org/food/integration/AccountIntegrationTest.java
> +        AccountDto response = objectMapper.readValue(contentAsString, AccountDto.class);
исправил

2024-02-04 16:12 UTC, drasolka requested changes

2024-02-04 16:12 UTC, drasolka commented on src/main/java/org/food/controller/OrderController.java
> +    @GetMapping("/meals/{id}")
Маппинг неверный: для получения списка блюд в заказе лучше будет `/orders/{orderId}/meals`.

2024-02-04 16:12 UTC, drasolka commented on src/main/java/org/food/model/Order.java
> +    @ManyToMany(fetch = FetchType.EAGER, targetEntity = Meal.class)
Какие будут проблемы при использовании `FetchType.EAGER`?

2024-02-04 16:12 UTC, drasolka commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
**НЕЛЬЗЯ** изменять скрипты миграции базы данных. Можно только добавлять новые миграции.

2024-02-04 16:12 UTC, drasolka commented on src/main/java/org/food/controller/AccountController.java
> +    public AccountDto addAccount(@RequestBody AccountDto accountDto) throws HttpMessageNotReadableException {
Это проверяемая или непроверяемая ошибка? Есть ли необходимость иметь эту ошибку в сигнатуре методов?

2024-02-05 08:09 UTC, drasolka commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
НЕЛЬЗЯ изменять скрипты миграции базы данных. Можно только добавлять новые миграции.

2024-02-05 08:09 UTC, drasolka commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
> +            <column name="timeq" type="int"/>
Какое бизнес значение у поля с таким именем?

2024-02-05 08:10 UTC, drasolka commented on src/test/java/org/food/service/AccountServiceImplTest.java
> +import static org.mockito.Mockito.*;
Вопрос об использовании * для импортов поднимался, но ничего не изменилось.

2024-02-05 08:11 UTC, drasolka commented on src/test/resources/db/data/testdata.sql
К какому тесту относятся данные? Из названия совершенно не понятно.

2024-02-05 09:23 UTC, SashaHapon commented on src/main/java/org/food/model/Order.java
> +    @ManyToMany(fetch = FetchType.EAGER, targetEntity = Meal.class)
основная N+1, уже исправил, менял потому что не мог найти причину ошибок в тестировании.

2024-02-05 09:25 UTC, SashaHapon commented on src/test/java/org/food/service/AccountServiceImplTest.java
> +import static org.mockito.Mockito.*;
Не подумай что я игнорирую замечания, просто идея сама правит это. Сейчас ещё раз просмотрю

2024-02-06 11:29 UTC, drasolka requested changes

2024-02-06 11:29 UTC, drasolka commented on src/test/java/org/food/TestUtils.java
Это сложно поддерживаемый класс. Его необходимо будет обновлять каждый раз при создании нового класса для тестов.
Лучше всего будет сделать базовый класс с одним методом:
```
protected String getJsonAsString(String fileName) throws IOException {
        return  Files.readString(ResourceUtils.getFile(fileName).toPath());
    }
```

Вызывать его следует так, н-р, в классе `src/test/java/org/food/controller/AccountControllerIntegrationTests.java`
```
private static final String TEST_DATA_FILE_PREFIX = "classpath:data/org/food/controller/AccountControllerIntegrationTest";
...

getJsonAsString(TEST_DATA_FILE_PREFIX + "/should_return_Account_with_id1/getAccount_expectedAccountDto.json")
```

2024-02-06 11:29 UTC, drasolka commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
НЕЛЬЗЯ изменять скрипты миграции базы данных. Можно только добавлять новые миграции.

2024-02-06 11:29 UTC, drasolka commented on src/main/java/org/food/controller/OrderController.java
> +    @GetMapping("/meals/{id}")
Актуальное замечание.

2024-02-06 12:53 UTC, drasolka approved these changes

2024-02-06 12:53 UTC, merged