#34
SashaHapon/Web pull request #43
Opened 2024-02-07 11:36 UTC by SashaHapon

2024-02-08 07:07 UTC, drasolka requested changes

2024-02-08 07:07 UTC, drasolka commented on pom.xml
> +        </dependency>
Нет необходимости в декларации этих зависимостей. Они являются транзитивными у `springdoc-openapi-starter-webmvc-ui`.

2024-02-08 07:07 UTC, drasolka commented on src/main/java/org/food/controller/AccountController.java
> +    @SecurityRequirement(name = "JWT")
Можно объявлять на уровне класса. Нет необходимости над каждым методом ставить(Над методом лучше ставить когда для разных методов используются разные типа авторизации).

2024-02-08 07:07 UTC, drasolka commented on src/main/java/org/food/dto/OrderDto.java
>  //
Нет необходимости, т.к. связь с пользователем происходит через поле `account`.

2024-02-08 07:07 UTC, drasolka commented on src/main/java/org/food/security/SecurityConfiguration.java
> +                        .requestMatchers("/swagger-ui/**").permitAll()
Необходимо добавить еще `swagger-ui.html`, т.к. согласно [документации ](https://springdoc.org/#getting-started) документация, сгенерированная swagger доступна по пути `http://server:port/context-path/swagger-ui.html`.

2024-02-08 07:07 UTC, drasolka commented on src/main/java/org/food/security/controller/AuthController.java
> +@Hidden
Зачем скрыты эти контроллеры от свагера?

2024-02-08 12:59 UTC, SashaHapon commented on src/main/java/org/food/security/controller/AuthController.java
> +@Hidden
судя моей логике, описание уровней безопасности не должно быть видно в общей документации. Сейчас исправлю

2024-02-08 21:18 UTC, drasolka requested changes

2024-02-08 21:18 UTC, drasolka commented on src/main/java/org/food/security/controller/AuthController.java
> +@Tag(name = "AccountController", description = " Позволяет контролировать аккаунты в бд")
Данные в теге не соответствуют классу.

2024-02-08 21:18 UTC, drasolka commented on pom.xml
> +<!--        </dependency>-->
Нет необходимости держать в комментариях эти зависимости. Это мертвый код.

2024-02-08 21:18 UTC, drasolka commented on src/main/java/org/food/security/controller/AuthController.java
> +            description = "Позволяет создать заказ в базе данных"
Данные в описании не соответствуют назначению метода.

2024-02-08 21:18 UTC, drasolka commented on src/main/java/org/food/security/controller/UserController.java
> +@Tag(name = "AccountController", description = " Позволяет получить полозователя из бд")
Данные в теге не соответствуют классу.

2024-02-09 07:12 UTC, drasolka requested changes

2024-02-09 07:12 UTC, drasolka commented on src/main/java/org/food/security/controller/UserController.java
> +@Tag(name = "AuthController", description = " Позволяет получить полозователя из бд")
Описание не совпадает с назначением.

2024-02-09 07:32 UTC, drasolka approved these changes

2024-02-09 07:32 UTC, merged