30
SashaHapon/Web pull request #45
Opened 2024-02-09 07:53 UTC by SashaHapon

2024-02-13 11:59 UTC, drasolka requested changes

2024-02-13 11:59 UTC, drasolka commented on src/main/java/org/food/dao/AbstractDao.java
> +        entityManager.remove(entityManager.contains(entity) ? entity : entityManager.merge(entity));
Нет необходимости проверять на наличие в entityManager. Лучше сначала получать объект, а потом удалять уже загруженный.

2024-02-13 11:59 UTC, drasolka commented on src/main/java/org/food/model/Account.java
Нет необходимости в переопределении методов и конструкторе.

2024-02-13 11:59 UTC, drasolka commented on src/main/java/org/food/model/Meal.java
Нет необходимости в переопределении методов и конструкторе.

2024-02-13 11:59 UTC, drasolka commented on src/main/java/org/food/model/Order.java
Нет необходимости в переопределении методов и конструкторе.

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/controller/MealControllerIntegrationTests.java
По задаче тестирование должно быть другого слоя приложения.

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/controller/OrderControllerIntegrationTests.java
По задаче тестирование должно быть другого слоя приложения.

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/dao/AccountRepositoryIntegrationTests.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
Попробуй убрать `(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)`.
Попробуй посмотреть подходит ли для подобного теста `@DataJpaTest`.

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/dao/AccountRepositoryIntegrationTests.java
> +        accountList = new ArrayList<>(List.of(account1, account2, account3, account4, account5));
Данные для тестов лучше содавать внутри конкретного теста следуя подходу:
given when then:
```@java
@Test
void testMethod(){
    //given
    // setup data for test
    
    //when
    // mock, stub, etc
    
    //then
    // check results
}
```

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/dao/MealRepositoryIntegrationTest.java
Аналогично AccountRepositoryIntegrationTests классу необходимо сделать изменения.

2024-02-13 11:59 UTC, drasolka commented on src/test/java/org/food/dao/OrderRepositoryIntegrationTest.java
Аналогично AccountRepositoryIntegrationTests классу необходимо сделать изменения.

2024-02-15 10:36 UTC, SashaHapon commented on src/test/java/org/food/dao/AccountRepositoryIntegrationTests.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
с @DataJPATest  не собирается

2024-02-15 10:42 UTC, drasolka requested changes

2024-02-15 10:42 UTC, drasolka commented on src/test/java/org/food/controller/MealControllerIntegrationTests.java
> +import org.junit.jupiter.api.BeforeAll;
Лишние импорты.

2024-02-15 10:42 UTC, drasolka commented on src/test/java/org/food/controller/MealControllerIntegrationTests.java
> +import org.testcontainers.containers.MySQLContainer;
Лишние импорты.

2024-02-15 10:45 UTC, drasolka approved these changes

2024-02-15 11:02 UTC, merged