46
SashaHapon/Web pull request #47
Opened 2024-02-15 14:08 UTC by SashaHapon

2024-02-19 07:26 UTC, drasolka requested changes

2024-02-19 07:26 UTC, drasolka commented on pom.xml
> +        </dependency>
Scope должен быть runtime.

2024-02-19 07:26 UTC, drasolka commented on pom.xml
>              <artifactId>mysql-connector-j</artifactId>
Scope должен быть runtime.

2024-02-19 07:26 UTC, drasolka commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
> +    <changeSet id="1-1" author="Alexandr Hapon" labels="example-label" context="example-context">
Никаких здесь изменений нет, зачем изменение id?

2024-02-19 07:26 UTC, drasolka commented on docker-compose-postgres.yml
> +
Пустые строки - плохое форматирование.

2024-02-19 07:26 UTC, drasolka commented on src/main/resources/application-mysql.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
Будет ли так работать? Где верхний уровень `spring:` в проперти?

2024-02-19 07:26 UTC, drasolka commented on src/main/resources/application-postgres.yml
> +    driver-class-name: org.postgresql.Driver
Будет ли так работать? Где верхний уровень `spring:` в проперти?

2024-02-19 07:26 UTC, drasolka commented on src/test/resources/application-mysqltest.yml
> +      enabled: true
Нет необходимости в тестах.

2024-02-19 07:26 UTC, drasolka commented on src/test/resources/application-mysqltest.yml
> +      ddl-auto: update
Мы же создаем базу через liquibase.

2024-02-19 07:26 UTC, drasolka commented on src/test/resources/application-postgrestest.yml
>    h2:
Нет необходимости в тестах.

2024-02-19 07:26 UTC, drasolka commented on src/main/java/org/food/model/Order.java
> +import jakarta.validation.constraints.Null;
Лишний импорт.

2024-02-19 08:17 UTC, SashaHapon commented on src/main/resources/db/changelog/changeset/create-projects-table.xml
> +    <changeSet id="1-1" author="Alexandr Hapon" labels="example-label" context="example-context">
там было изменение, которое оказалось не нужным, а вернуть id забыл

2024-02-19 08:22 UTC, SashaHapon commented on src/test/resources/application-mysqltest.yml
> +      ddl-auto: update
использовал для проверки, забыл убрать

2024-02-19 08:25 UTC, SashaHapon commented on src/main/resources/application-mysql.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
не будет, исправил

2024-02-19 08:52 UTC, drasolka requested changes

2024-02-19 08:52 UTC, drasolka commented on README.md
> +./mvnw test -Dspring.profiles.active=postgrestets
Опечатка в имени профайла.

2024-02-19 08:52 UTC, drasolka commented on src/test/resources/application-mysqltest.yml
Почему пропал файл?
Он ведь нужен для интеграционных тестов, которые используют h2.

2024-02-19 09:57 UTC, SashaHapon commented on src/test/resources/application-mysqltest.yml
поправил, разбирался почему не получалось подтягивать профайл для контейнера, а подтягивался тестовый

2024-02-19 12:26 UTC, drasolka requested changes

2024-02-19 12:26 UTC, drasolka commented on README.md
Need to update according discussion.

2024-02-21 07:14 UTC, drasolka approved these changes

2024-02-21 07:14 UTC, merged