#51 kafka
SashaHapon/Web pull request #55
Opened 2024-03-03 07:45 UTC by SashaHapon

2024-03-05 13:10 UTC, drasolka requested changes
- [ ] Необходимо обновить README с актуальной информацией о сервисах.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/main/java/org/food/api/service/OrderService.java
> +    OrderDto createOrder(Integer accountId, List<MealDto> mealDtoList) throws JsonProcessingException;
Нет необходимости в JsonProcessingException в сигнатуре метода.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/main/java/org/food/config/KafkaConfig.java
Нет необходимости в этом классе.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/main/java/org/food/controller/OrderController.java
> +                                List<MealDto> mealDtoList) throws JsonProcessingException {
JsonProcessingException не нужна.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/main/java/org/food/service/OrderServiceImpl.java
> +        Order order = modelMapper.map(orderDto, Order.class);
Здесь должна быть загрузка ордера из базы.
Изменение его информации, а затем сохранение.

- [ ] Что произойдет в случае, если такого ордера в базе не существует?

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/test/java/org/food/controller/OrderControllerIntegrationTests.java
> +                .andReturn();
Не нужно возвращать ничего здесь.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/test/java/org/food/controller/OrderControllerIntegrationTests.java
> +@Import(ContainerConfiguration.class)
Вроде бы не нужно здесь импортить конфигурацию.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/test/java/org/food/dao/OrderRepositoryIntegrationTests.java
Необходимо поправить форматирование кода.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/test/java/org/food/service/OrderServiceImplTests.java
> +    public void should_returnOrder_whenTryToCreateOrder() throws JsonProcessingException {
Не нужно throws JsonProcessingException в сигнатуре.

2024-03-05 13:10 UTC, drasolka commented on order-manager/src/test/resources/application-h2.yml
> +  kafka:
Необходимы ли данные проперти?

2024-03-05 20:58 UTC, SashaHapon commented on order-manager/src/main/java/org/food/service/OrderServiceImpl.java
> +        Order order = modelMapper.map(orderDto, Order.class);
PersistenceException

2024-03-05 21:33 UTC, SashaHapon commented on order-manager/src/test/resources/application-h2.yml
> +  kafka:
нет

2024-03-06 07:07 UTC, drasolka requested changes
Не обновлена информация в README в order-manager проекте.

2024-03-06 07:07 UTC, drasolka commented on order-manager/src/main/java/org/food/controller/OrderController.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Лишний импорт.

2024-03-06 07:07 UTC, drasolka commented on order-manager/src/main/java/org/food/service/OrderServiceImpl.java
> +        Order order = modelMapper.map(orderDto, Order.class);
Почему бы сразу не изменять данные в ордере из дто объекта? Зачем мапить из дто в модель?

2024-03-06 07:07 UTC, drasolka commented on order-manager/src/test/java/org/food/dao/OrderRepositoryIntegrationTests.java
> +
Форматирование кода.

2024-03-06 07:07 UTC, drasolka commented on order-manager/src/test/java/org/food/service/OrderServiceImplTests.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Лишний импорт.

2024-03-06 07:07 UTC, drasolka commented on order-manager/src/test/java/org/food/service/OrderServiceImplTests.java
> +    public void should_returnOrder_whenTryToCreateOrder(){
Форматирование.

2024-03-06 07:12 UTC, SashaHapon commented on order-manager/src/main/java/org/food/service/OrderServiceImpl.java
> +        Order order = modelMapper.map(orderDto, Order.class);
мапить все равно придется что-то, либо OrderDto или MealDto

2024-03-06 07:59 UTC, drasolka approved these changes

2024-03-06 08:02 UTC, merged